---
wildfly_systemd:
  user: "{{ wildfly_user }}"
  group: "{{ wildfly_group }}"
  home: "{{ wildfly_home }}"
  config: "{{ wildfly_config_base }}"
  enabled: "{{ wildfly_systemd_enabled }}"
  yml_config:
    base_path: '/modules/system/layers/base'
    eap_path: 'modules/system/layers/base/.overlays/layer-base-jboss-eap-'
    path: /org/jboss/as/controller/main/dir/META-INF/services
    file: org.jboss.as.controller.persistence.ConfigurationExtension