---
- name: "Ensure required params for JBoss CLI have been provided"
  ansible.builtin.assert:
    that:
      - jboss_home is defined
      - query is defined
      - jboss_cli_controller_host is defined
      - jboss_cli_controller_port is defined
    fail_msg: "Missing required parameters to execute JBoss CLI."
    quiet: true

- name: "Ensure server's management interface is reachable"
  ansible.builtin.wait_for:
    host: "{{ jboss_cli_controller_host }}"
    port: "{{ jboss_cli_controller_port }}"

- name: "Execute CLI query: {{ query }}"
  ansible.builtin.command: >
    {{ jboss_cli_path_to_script | default(jboss_home + '/bin/jboss-cli.sh') }} -c --output-json --command={{ query }} --controller={{ jboss_cli_controller_host }}:{{ jboss_cli_controller_port }}
  register: cli_result
  changed_when: false
  become: yes
  retries: 3
  delay: 5
