ancestor: 0.2.6
releases:
  1.0.0:
    changes:
      release_summary: 'This is the first stable release of the ``middleware_automation.keycloak``
        collection.

        '
    release_date: '2022-03-04'
  1.0.1:
    changes:
      major_changes:
      - Apply latest cumulative patch of RH-SSO automatically when new parameter ``keycloak_rhsso_apply_patches``
        is ``true`` `#18 <https://github.com/ansible-middleware/keycloak/pull/18>`_
      minor_changes:
      - Clustered installs now perform database initialization on first node to avoid
        locking issues `#17 <https://github.com/ansible-middleware/keycloak/pull/17>`_
      release_summary: 'Minor enhancements, bug and documentation fixes.

        '
    release_date: '2022-03-11'
  1.0.2:
    changes:
      bugfixes:
      - 'Set ``keycloak_frontend_url`` default according to other defaults `#25 <https://github.com/ansible-middleware/keycloak/pull/25>`_

        '
      minor_changes:
      - 'Make ``keycloak_admin_password`` a default with assert (was: role variable)
        `#26 <https://github.com/ansible-middleware/keycloak/pull/26>`_

        '
      - 'Simplify dependency install logic and reduce play execution time `#19 <https://github.com/ansible-middleware/keycloak/pull/19>`_

        '
    fragments:
    - 19.yaml
    - 25.yaml
    - 26.yaml
    release_date: '2022-04-01'
  1.0.3:
    changes:
      bugfixes:
      - 'Make sure systemd unit starts with selected java JVM `#31 <https://github.com/ansible-middleware/keycloak/pull/31>`_

        '
      major_changes:
      - 'New role for installing keycloak >= 17.0.0 (quarkus) `#29 <https://github.com/ansible-middleware/keycloak/pull/29>`_

        '
      minor_changes:
      - 'Add ``keycloak_config_override_template`` parameter for passing a custom
        xml config template `#30 <https://github.com/ansible-middleware/keycloak/pull/30>`_

        '
    fragments:
    - 29.yaml
    - 30.yaml
    - 31.yaml
    release_date: '2022-05-09'
  1.0.4:
    release_date: '2022-05-11'
  1.0.5:
    changes:
      minor_changes:
      - 'Update config options: keycloak and quarkus `#32 <https://github.com/ansible-middleware/keycloak/pull/32>`_

        '
    fragments:
    - 32.yaml
    release_date: '2022-05-25'
  1.0.6:
    changes:
      bugfixes:
      - 'keycloak_quarkus: add selected java to PATH in systemd unit `#34 <https://github.com/ansible-middleware/keycloak/pull/34>`_

        '
      - 'keycloak_quarkus: set logfile path correctly under keycloak home `#35 <https://github.com/ansible-middleware/keycloak/pull/35>`_

        '
    fragments:
    - 34.yaml
    - 35.yaml
    release_date: '2022-06-01'
