argument_specs:
    main:
        options:
            jboss_cli_controller_host:
                # line 2 of jboss_eap/defaults/main.yml
                default: "localhost"
                description: "Hostname for connecting to cli"
                type: "str"
            jboss_cli_controller_port:
                # line 3 of jboss_eap/defaults/main.yml
                default: "9990"
                description: "Port for connecting to cli"
                type: "str"
            wildfly_user:
                # line 10 of wildfly_install/defaults/main.yml
                default: "wildfly"
                description: "posix user account for wildfly"
                type: "str"
            wildfly_group:
                # line 11 of wildfly_install/defaults/main.yml
                default: "{{ wildfly_user }}"
                description: "posix group for wildfly"
                type: "str"
            wildfly_version:
                default: "26.0.0.Final"
                description: "Wildfly version to install"
                type: "str"
            wildfly_home:
                required: True
                description: "Wildfly installation directory"
                type: "str"
            jboss_home:
                default: "{{ wildfly_home }}"
                description: "Wildfly installation directory, for backwards compatibility"
                type: "str"
            wildfly_no_restart_after_patch:
                default: False
                description: "When true, skip restarting after applying a cumulative patch"
                type: "bool"
    downstream:
        options:
            eap_enable:
                default: True
                description: "Enable install of Red Hat JBoss EAP"
                type: "bool"
            eap_apply_cp:
                default: false
                description: "Whether to apply the latest cumulative patch on top of baseline version"
                type: "bool"
            eap_version:
                default: "7.4.0"
                description: "Red Hat EAP version to install"
                type: "str"
            eap_patch_version:
                default: "7.4.5"
                description: "Red Hat EAP cumulative patch version to install"
                type: "str"
            eap_install_workdir:
                default: "/opt/jboss_eap/"
                description: "Root directory for installation"
                type: "str"
            eap_home:
                default: "{{ eap_install_workdir }}jboss-eap-{{ (eap_version | split('.'))[0:2] | join('.') }}/"
                description: "Red Hat EAP installation path"
                type: "str"
            eap_offline_install:
                default: True
                description: "Whether to install from local archive"
                type: "bool"
            eap_install_rhn_id:
                default: "99481"
                description: "Red Hat EAP CSP download ID"
                type: "str"
            eap_patch_install_rhn_id:
                default: "99481"
                description: "Red Hat EAP cumulative patch CSP download ID"
                type: "str"
            eap_apply_cp_verbose:
                default: False
                description: "Whether to output verbose patch output"
                type: "bool"
    jboss_cli:
        options:
            jboss_cli_controller_host:
                # line 2 of jboss_eap/defaults/main.yml
                default: "localhost"
                description: "Hostname for connecting to cli"
                type: "str"
            jboss_cli_controller_port:
                # line 3 of jboss_eap/defaults/main.yml
                default: "9990"
                description: "Port for connecting to cli"
                type: "str"
            query:
                required: True
                description: "The command to sed to jboss-cli"
                type: "str"